AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'features/support/*.rb'
Documentation:
  Enabled: false
Metrics/LineLength:
  Exclude:
    - 'db/seeds.rb'
    - 'features/step_definitions/*.rb'
Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'features/step_definitions/*.rb'
